version: '3'

services:
  pokedexapp:
    depends_on:
      - pokedex
    build: 
      context: .
      dockerfile: Dockerfile
    image: pokedex-docker
    container_name: pokedexapp
    restart: always
    ports:
      - "${PORT}:${PORT}"
    environment:
      MONGODB: ${MONGODB}
      PORT: ${PORT}
      DEFAULT_LIMIT: ${DEFAULT_LIMIT}
    networks:
      - pokedex_network

  pokedex:
    image: mongo:5
    container_name: pokedex
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGODB_DATABASE: pokedex
    networks:
      - pokedex_network

networks:
  pokedex_network:
    driver: bridge
